import 'package:flutter_test/flutter_test.dart';
import 'package:guoxueapp/tool/calendar/solar_term_candidate_landing_reviewer.dart';

void main() {
  final r = const SolarTermCandidateLandingReviewer();

  group('source review gates', () {
    test('missing→source_review_missing',()=>expect(r.review(const SolarTermCandidateLandingReviewInput()).status,'source_review_missing'));
    test('hard rejected→source_hard_rejected',()=>expect(r.review(SolarTermCandidateLandingReviewInput(sourceReviewReportExists:true,sourceReviewHardRejected:true)).status,'source_hard_rejected'));
    test('not approved→source_not_approved',()=>expect(r.review(SolarTermCandidateLandingReviewInput(sourceReviewReportExists:true,sourceReviewLevel:'review_required')).status,'source_not_approved'));
  });

  group('preparation gates', () {
    test('no report→preparation_report_missing',()=>expect(r.review(SolarTermCandidateLandingReviewInput(sourceReviewReportExists:true,sourceReviewLevel:'approved_for_candidate_preparation')).status,'preparation_report_missing'));
    test('not ready→preparation_not_ready',()=>expect(r.review(SolarTermCandidateLandingReviewInput(sourceReviewReportExists:true,sourceReviewLevel:'approved_for_candidate_preparation',preparationReportExists:true,preparationStatus:'not_started')).status,'preparation_not_ready'));
  });

  group('data file gates', () {
    final b = SolarTermCandidateLandingReviewInput(sourceReviewReportExists:true,sourceReviewLevel:'approved_for_candidate_preparation',preparationReportExists:true,preparationStatus:'ready_for_candidate_sandbox');
    test('raw missing→raw_data_missing',()=>expect(r.review(b).status,'raw_data_missing'));
    test('landed missing',()=>expect(r.review(SolarTermCandidateLandingReviewInput(sourceReviewReportExists:true,sourceReviewLevel:'approved_for_candidate_preparation',preparationReportExists:true,preparationStatus:'ready_for_candidate_sandbox',rawCandidateDataExists:true)).status,'landed_file_missing'));
    test('manifest missing',()=>expect(r.review(SolarTermCandidateLandingReviewInput(sourceReviewReportExists:true,sourceReviewLevel:'approved_for_candidate_preparation',preparationReportExists:true,preparationStatus:'ready_for_candidate_sandbox',rawCandidateDataExists:true,landedCandidateFileExists:true)).status,'manifest_missing'));
    test('schema missing',()=>expect(r.review(SolarTermCandidateLandingReviewInput(sourceReviewReportExists:true,sourceReviewLevel:'approved_for_candidate_preparation',preparationReportExists:true,preparationStatus:'ready_for_candidate_sandbox',rawCandidateDataExists:true,landedCandidateFileExists:true,manifestExists:true)).status,'schema_missing'));
    test('checksum missing',()=>expect(r.review(SolarTermCandidateLandingReviewInput(sourceReviewReportExists:true,sourceReviewLevel:'approved_for_candidate_preparation',preparationReportExists:true,preparationStatus:'ready_for_candidate_sandbox',rawCandidateDataExists:true,landedCandidateFileExists:true,manifestExists:true,schemaExists:true)).status,'checksum_missing'));
  });

  group('source match gates', () {
    final b = SolarTermCandidateLandingReviewInput(sourceReviewReportExists:true,sourceReviewLevel:'approved_for_candidate_preparation',preparationReportExists:true,preparationStatus:'ready_for_candidate_sandbox',rawCandidateDataExists:true,landedCandidateFileExists:true,manifestExists:true,schemaExists:true,checksumExists:true);
    test('name mismatch',()=>expect(r.review(b).status,'source_name_mismatch'));
    test('type mismatch',()=>expect(r.review(SolarTermCandidateLandingReviewInput(sourceReviewReportExists:true,sourceReviewLevel:'approved_for_candidate_preparation',preparationReportExists:true,preparationStatus:'ready_for_candidate_sandbox',rawCandidateDataExists:true,landedCandidateFileExists:true,manifestExists:true,schemaExists:true,checksumExists:true,sourceNameMatchesReview:true)).status,'source_type_mismatch'));
    test('license missing',()=>expect(r.review(SolarTermCandidateLandingReviewInput(sourceReviewReportExists:true,sourceReviewLevel:'approved_for_candidate_preparation',preparationReportExists:true,preparationStatus:'ready_for_candidate_sandbox',rawCandidateDataExists:true,landedCandidateFileExists:true,manifestExists:true,schemaExists:true,checksumExists:true,sourceNameMatchesReview:true,sourceTypeMatchesReview:true)).status,'license_missing'));
  });

  group('coverage gates', () {
    final b = SolarTermCandidateLandingReviewInput(sourceReviewReportExists:true,sourceReviewLevel:'approved_for_candidate_preparation',preparationReportExists:true,preparationStatus:'ready_for_candidate_sandbox',rawCandidateDataExists:true,landedCandidateFileExists:true,manifestExists:true,schemaExists:true,checksumExists:true,sourceNameMatchesReview:true,sourceTypeMatchesReview:true,licenseAttached:true);
    test('coverage incomplete',()=>expect(r.review(b).status,'coverage_incomplete'));
    test('term incomplete',()=>expect(r.review(SolarTermCandidateLandingReviewInput(sourceReviewReportExists:true,sourceReviewLevel:'approved_for_candidate_preparation',preparationReportExists:true,preparationStatus:'ready_for_candidate_sandbox',rawCandidateDataExists:true,landedCandidateFileExists:true,manifestExists:true,schemaExists:true,checksumExists:true,sourceNameMatchesReview:true,sourceTypeMatchesReview:true,licenseAttached:true,coverageStartYear:1900,coverageEndYear:2100)).status,'term_coverage_incomplete'));
    test('date missing',()=>expect(r.review(SolarTermCandidateLandingReviewInput(sourceReviewReportExists:true,sourceReviewLevel:'approved_for_candidate_preparation',preparationReportExists:true,preparationStatus:'ready_for_candidate_sandbox',rawCandidateDataExists:true,landedCandidateFileExists:true,manifestExists:true,schemaExists:true,checksumExists:true,sourceNameMatchesReview:true,sourceTypeMatchesReview:true,licenseAttached:true,coverageStartYear:1900,coverageEndYear:2100,coversAll24Terms:true)).status,'term_date_missing'));
    test('time missing',()=>expect(r.review(SolarTermCandidateLandingReviewInput(sourceReviewReportExists:true,sourceReviewLevel:'approved_for_candidate_preparation',preparationReportExists:true,preparationStatus:'ready_for_candidate_sandbox',rawCandidateDataExists:true,landedCandidateFileExists:true,manifestExists:true,schemaExists:true,checksumExists:true,sourceNameMatchesReview:true,sourceTypeMatchesReview:true,licenseAttached:true,coverageStartYear:1900,coverageEndYear:2100,coversAll24Terms:true,hasTermDate:true)).status,'term_time_missing'));
    test('timezone missing',()=>expect(r.review(SolarTermCandidateLandingReviewInput(sourceReviewReportExists:true,sourceReviewLevel:'approved_for_candidate_preparation',preparationReportExists:true,preparationStatus:'ready_for_candidate_sandbox',rawCandidateDataExists:true,landedCandidateFileExists:true,manifestExists:true,schemaExists:true,checksumExists:true,sourceNameMatchesReview:true,sourceTypeMatchesReview:true,licenseAttached:true,coverageStartYear:1900,coverageEndYear:2100,coversAll24Terms:true,hasTermDate:true,hasTermTime:true)).status,'timezone_missing'));
  });

  group('production guard gates', () {
    final b = SolarTermCandidateLandingReviewInput(sourceReviewReportExists:true,sourceReviewLevel:'approved_for_candidate_preparation',preparationReportExists:true,preparationStatus:'ready_for_candidate_sandbox',rawCandidateDataExists:true,landedCandidateFileExists:true,manifestExists:true,schemaExists:true,checksumExists:true,sourceNameMatchesReview:true,sourceTypeMatchesReview:true,licenseAttached:true,coverageStartYear:1900,coverageEndYear:2100,coversAll24Terms:true,hasTermDate:true,hasTermTime:true,timezoneSpecified:true);
    test('productionReady true→rejected',()=>expect(r.review(SolarTermCandidateLandingReviewInput(sourceReviewReportExists:true,sourceReviewLevel:'approved_for_candidate_preparation',preparationReportExists:true,preparationStatus:'ready_for_candidate_sandbox',rawCandidateDataExists:true,landedCandidateFileExists:true,manifestExists:true,schemaExists:true,checksumExists:true,sourceNameMatchesReview:true,sourceTypeMatchesReview:true,licenseAttached:true,coverageStartYear:1900,coverageEndYear:2100,coversAll24Terms:true,hasTermDate:true,hasTermTime:true,timezoneSpecified:true,productionReady:true)).status,'rejected_production_ready_true'));
    test('publicExposure true→rejected',()=>expect(r.review(SolarTermCandidateLandingReviewInput(sourceReviewReportExists:true,sourceReviewLevel:'approved_for_candidate_preparation',preparationReportExists:true,preparationStatus:'ready_for_candidate_sandbox',rawCandidateDataExists:true,landedCandidateFileExists:true,manifestExists:true,schemaExists:true,checksumExists:true,sourceNameMatchesReview:true,sourceTypeMatchesReview:true,licenseAttached:true,coverageStartYear:1900,coverageEndYear:2100,coversAll24Terms:true,hasTermDate:true,hasTermTime:true,timezoneSpecified:true,publicExposure:true)).status,'rejected_public_exposure_true'));
    test('calendarProviderIntegration true→rejected',()=>expect(r.review(SolarTermCandidateLandingReviewInput(sourceReviewReportExists:true,sourceReviewLevel:'approved_for_candidate_preparation',preparationReportExists:true,preparationStatus:'ready_for_candidate_sandbox',rawCandidateDataExists:true,landedCandidateFileExists:true,manifestExists:true,schemaExists:true,checksumExists:true,sourceNameMatchesReview:true,sourceTypeMatchesReview:true,licenseAttached:true,coverageStartYear:1900,coverageEndYear:2100,coversAll24Terms:true,hasTermDate:true,hasTermTime:true,timezoneSpecified:true,calendarProviderIntegration:true)).status,'rejected_calendar_provider_integration'));
  });

  group('verification gates', () {
    final b = SolarTermCandidateLandingReviewInput(sourceReviewReportExists:true,sourceReviewLevel:'approved_for_candidate_preparation',preparationReportExists:true,preparationStatus:'ready_for_candidate_sandbox',rawCandidateDataExists:true,landedCandidateFileExists:true,manifestExists:true,schemaExists:true,checksumExists:true,sourceNameMatchesReview:true,sourceTypeMatchesReview:true,licenseAttached:true,coverageStartYear:1900,coverageEndYear:2100,coversAll24Terms:true,hasTermDate:true,hasTermTime:true,timezoneSpecified:true);
    test('sandbox failed',()=>expect(r.review(b).status,'sandbox_failed'));
    test('preflight failed',()=>expect(r.review(SolarTermCandidateLandingReviewInput(sourceReviewReportExists:true,sourceReviewLevel:'approved_for_candidate_preparation',preparationReportExists:true,preparationStatus:'ready_for_candidate_sandbox',rawCandidateDataExists:true,landedCandidateFileExists:true,manifestExists:true,schemaExists:true,checksumExists:true,sourceNameMatchesReview:true,sourceTypeMatchesReview:true,licenseAttached:true,coverageStartYear:1900,coverageEndYear:2100,coversAll24Terms:true,hasTermDate:true,hasTermTime:true,timezoneSpecified:true,sandboxPassed:true)).status,'preflight_failed'));
    test('validator failed',()=>expect(r.review(SolarTermCandidateLandingReviewInput(sourceReviewReportExists:true,sourceReviewLevel:'approved_for_candidate_preparation',preparationReportExists:true,preparationStatus:'ready_for_candidate_sandbox',rawCandidateDataExists:true,landedCandidateFileExists:true,manifestExists:true,schemaExists:true,checksumExists:true,sourceNameMatchesReview:true,sourceTypeMatchesReview:true,licenseAttached:true,coverageStartYear:1900,coverageEndYear:2100,coversAll24Terms:true,hasTermDate:true,hasTermTime:true,timezoneSpecified:true,sandboxPassed:true,preflightPassed:true)).status,'validator_failed'));
    test('cross-check failed',()=>expect(r.review(SolarTermCandidateLandingReviewInput(sourceReviewReportExists:true,sourceReviewLevel:'approved_for_candidate_preparation',preparationReportExists:true,preparationStatus:'ready_for_candidate_sandbox',rawCandidateDataExists:true,landedCandidateFileExists:true,manifestExists:true,schemaExists:true,checksumExists:true,sourceNameMatchesReview:true,sourceTypeMatchesReview:true,licenseAttached:true,coverageStartYear:1900,coverageEndYear:2100,coversAll24Terms:true,hasTermDate:true,hasTermTime:true,timezoneSpecified:true,sandboxPassed:true,preflightPassed:true,validatorPassed:true)).status,'cross_check_failed'));
    test('reference fixture failed',()=>expect(r.review(SolarTermCandidateLandingReviewInput(sourceReviewReportExists:true,sourceReviewLevel:'approved_for_candidate_preparation',preparationReportExists:true,preparationStatus:'ready_for_candidate_sandbox',rawCandidateDataExists:true,landedCandidateFileExists:true,manifestExists:true,schemaExists:true,checksumExists:true,sourceNameMatchesReview:true,sourceTypeMatchesReview:true,licenseAttached:true,coverageStartYear:1900,coverageEndYear:2100,coversAll24Terms:true,hasTermDate:true,hasTermTime:true,timezoneSpecified:true,sandboxPassed:true,preflightPassed:true,validatorPassed:true,crossCheckPassed:true)).status,'reference_fixture_failed'));
    test('manual review failed',()=>expect(r.review(SolarTermCandidateLandingReviewInput(sourceReviewReportExists:true,sourceReviewLevel:'approved_for_candidate_preparation',preparationReportExists:true,preparationStatus:'ready_for_candidate_sandbox',rawCandidateDataExists:true,landedCandidateFileExists:true,manifestExists:true,schemaExists:true,checksumExists:true,sourceNameMatchesReview:true,sourceTypeMatchesReview:true,licenseAttached:true,coverageStartYear:1900,coverageEndYear:2100,coversAll24Terms:true,hasTermDate:true,hasTermTime:true,timezoneSpecified:true,sandboxPassed:true,preflightPassed:true,validatorPassed:true,crossCheckPassed:true,referenceFixturePassed:true)).status,'manual_review_failed'));
  });

  group('rejection gates', () {
    final b = SolarTermCandidateLandingReviewInput(sourceReviewReportExists:true,sourceReviewLevel:'approved_for_candidate_preparation',preparationReportExists:true,preparationStatus:'ready_for_candidate_sandbox',rawCandidateDataExists:true,landedCandidateFileExists:true,manifestExists:true,schemaExists:true,checksumExists:true,sourceNameMatchesReview:true,sourceTypeMatchesReview:true,licenseAttached:true,coverageStartYear:1900,coverageEndYear:2100,coversAll24Terms:true,hasTermDate:true,hasTermTime:true,timezoneSpecified:true,sandboxPassed:true,preflightPassed:true,validatorPassed:true,crossCheckPassed:true,referenceFixturePassed:true,manualReviewPassed:true);
    test('ai rejected',()=>expect(r.review(SolarTermCandidateLandingReviewInput(sourceReviewReportExists:true,sourceReviewLevel:'approved_for_candidate_preparation',preparationReportExists:true,preparationStatus:'ready_for_candidate_sandbox',rawCandidateDataExists:true,landedCandidateFileExists:true,manifestExists:true,schemaExists:true,checksumExists:true,sourceNameMatchesReview:true,sourceTypeMatchesReview:true,licenseAttached:true,coverageStartYear:1900,coverageEndYear:2100,coversAll24Terms:true,hasTermDate:true,hasTermTime:true,timezoneSpecified:true,sandboxPassed:true,preflightPassed:true,validatorPassed:true,crossCheckPassed:true,referenceFixturePassed:true,manualReviewPassed:true,usesAiGeneratedData:true)).status,'rejected_ai_generated'));
    test('network rejected',()=>expect(r.review(SolarTermCandidateLandingReviewInput(sourceReviewReportExists:true,sourceReviewLevel:'approved_for_candidate_preparation',preparationReportExists:true,preparationStatus:'ready_for_candidate_sandbox',rawCandidateDataExists:true,landedCandidateFileExists:true,manifestExists:true,schemaExists:true,checksumExists:true,sourceNameMatchesReview:true,sourceTypeMatchesReview:true,licenseAttached:true,coverageStartYear:1900,coverageEndYear:2100,coversAll24Terms:true,hasTermDate:true,hasTermTime:true,timezoneSpecified:true,sandboxPassed:true,preflightPassed:true,validatorPassed:true,crossCheckPassed:true,referenceFixturePassed:true,manualReviewPassed:true,requiresNetwork:true)).status,'rejected_network_dependency'));
    test('fixed date rejected',()=>expect(r.review(SolarTermCandidateLandingReviewInput(sourceReviewReportExists:true,sourceReviewLevel:'approved_for_candidate_preparation',preparationReportExists:true,preparationStatus:'ready_for_candidate_sandbox',rawCandidateDataExists:true,landedCandidateFileExists:true,manifestExists:true,schemaExists:true,checksumExists:true,sourceNameMatchesReview:true,sourceTypeMatchesReview:true,licenseAttached:true,coverageStartYear:1900,coverageEndYear:2100,coversAll24Terms:true,hasTermDate:true,hasTermTime:true,timezoneSpecified:true,sandboxPassed:true,preflightPassed:true,validatorPassed:true,crossCheckPassed:true,referenceFixturePassed:true,manualReviewPassed:true,usesFixedDateApproximation:true)).status,'rejected_fixed_date_approximation'));
  });

  group('ready', () {
    test('all pass→ready_for_production_review',() {
      final o=r.review(r.baseApproved);
      expect(o.status,'ready_for_production_review');
      expect(o.readyForNextStage,true);
    });
    test('ready→productionReady=false',()=>expect(r.review(r.baseApproved).productionReady,false));
    test('ready→publicExposure=false',()=>expect(r.review(r.baseApproved).publicExposure,false));
    test('ready→calendarProviderIntegration=false',()=>expect(r.review(r.baseApproved).calendarProviderIntegration,false));
    test('schemaVersion correct',()=>expect(r.review(r.baseApproved).schemaVersion,'solar-term-candidate-landing-review-v0_25'));
    test('no AI/network',() { final o=r.review(r.baseApproved); expect(o.publicExposure,false); expect(o.productionReady,false); });
  });
}
