import 'package:flutter_test/flutter_test.dart';
import 'package:guoxueapp/tool/calendar/solar_term_candidate_manual_reviewer.dart';

void main() {
  final r = const SolarTermCandidateManualReviewer();
  final a = SolarTermCandidateManualReviewer.allApproved;

  group('gate', () {
    test('source',()=>expect(r.review(const SolarTermCandidateManualReviewInput()).status,'source_review_not_approved'));
    test('prep',()=>expect(r.review(SolarTermCandidateManualReviewInput(sourceReviewApproved:true)).status,'preparation_not_ready'));
    test('landing',()=>expect(r.review(SolarTermCandidateManualReviewInput(sourceReviewApproved:true,preparationReady:true)).status,'landing_review_not_ready'));
    test('sandbox',()=>expect(r.review(SolarTermCandidateManualReviewInput(sourceReviewApproved:true,preparationReady:true,landingReviewReady:true)).status,'sandbox_not_safe'));
    test('preflight',()=>expect(r.review(SolarTermCandidateManualReviewInput(sourceReviewApproved:true,preparationReady:true,landingReviewReady:true,sandboxSafe:true)).status,'preflight_not_passed'));
    test('validator',()=>expect(r.review(SolarTermCandidateManualReviewInput(sourceReviewApproved:true,preparationReady:true,landingReviewReady:true,sandboxSafe:true,preflightPassed:true)).status,'validator_not_passed'));
    test('crossCheck',()=>expect(r.review(SolarTermCandidateManualReviewInput(sourceReviewApproved:true,preparationReady:true,landingReviewReady:true,sandboxSafe:true,preflightPassed:true,validatorPassed:true)).status,'cross_check_not_passed'));
  });

  group('safety', () {
    final b = SolarTermCandidateManualReviewInput(sourceReviewApproved:true,preparationReady:true,landingReviewReady:true,sandboxSafe:true,preflightPassed:true,validatorPassed:true,crossCheckPassed:true);
    test('prodReady',()=>expect(r.review(SolarTermCandidateManualReviewInput(sourceReviewApproved:true,preparationReady:true,landingReviewReady:true,sandboxSafe:true,preflightPassed:true,validatorPassed:true,crossCheckPassed:true,productionReady:true)).status,'rejected_production_ready_true'));
    test('pubExp',()=>expect(r.review(SolarTermCandidateManualReviewInput(sourceReviewApproved:true,preparationReady:true,landingReviewReady:true,sandboxSafe:true,preflightPassed:true,validatorPassed:true,crossCheckPassed:true,publicExposure:true)).status,'rejected_public_exposure_true'));
    test('calProv',()=>expect(r.review(SolarTermCandidateManualReviewInput(sourceReviewApproved:true,preparationReady:true,landingReviewReady:true,sandboxSafe:true,preflightPassed:true,validatorPassed:true,crossCheckPassed:true,calendarProviderIntegration:true)).status,'rejected_calendar_provider_integration'));
  });

  group('confirmations', () {
    final b = SolarTermCandidateManualReviewInput(sourceReviewApproved:true,preparationReady:true,landingReviewReady:true,sandboxSafe:true,preflightPassed:true,validatorPassed:true,crossCheckPassed:true);
    test('source',()=>expect(r.review(b).status,'source_not_confirmed'));
    test('license',()=>expect(r.review(SolarTermCandidateManualReviewInput(sourceReviewApproved:true,preparationReady:true,landingReviewReady:true,sandboxSafe:true,preflightPassed:true,validatorPassed:true,crossCheckPassed:true,sourceManuallyConfirmed:true)).status,'license_not_confirmed'));
    test('embedding',()=>expect(r.review(SolarTermCandidateManualReviewInput(sourceReviewApproved:true,preparationReady:true,landingReviewReady:true,sandboxSafe:true,preflightPassed:true,validatorPassed:true,crossCheckPassed:true,sourceManuallyConfirmed:true,licenseManuallyConfirmed:true)).status,'embedding_permission_not_confirmed'));
    test('offline',()=>expect(r.review(SolarTermCandidateManualReviewInput(sourceReviewApproved:true,preparationReady:true,landingReviewReady:true,sandboxSafe:true,preflightPassed:true,validatorPassed:true,crossCheckPassed:true,sourceManuallyConfirmed:true,licenseManuallyConfirmed:true,embeddingAllowedConfirmed:true)).status,'offline_not_confirmed'));
    test('ai',()=>expect(r.review(SolarTermCandidateManualReviewInput(sourceReviewApproved:true,preparationReady:true,landingReviewReady:true,sandboxSafe:true,preflightPassed:true,validatorPassed:true,crossCheckPassed:true,sourceManuallyConfirmed:true,licenseManuallyConfirmed:true,embeddingAllowedConfirmed:true,offlineConfirmed:true)).status,'ai_generated_not_rejected'));
    test('fixedDate',()=>expect(r.review(SolarTermCandidateManualReviewInput(sourceReviewApproved:true,preparationReady:true,landingReviewReady:true,sandboxSafe:true,preflightPassed:true,validatorPassed:true,crossCheckPassed:true,sourceManuallyConfirmed:true,licenseManuallyConfirmed:true,embeddingAllowedConfirmed:true,offlineConfirmed:true,nonAiGeneratedConfirmed:true)).status,'fixed_date_approximation_not_rejected'));
    test('coverage',()=>expect(r.review(SolarTermCandidateManualReviewInput(sourceReviewApproved:true,preparationReady:true,landingReviewReady:true,sandboxSafe:true,preflightPassed:true,validatorPassed:true,crossCheckPassed:true,sourceManuallyConfirmed:true,licenseManuallyConfirmed:true,embeddingAllowedConfirmed:true,offlineConfirmed:true,nonAiGeneratedConfirmed:true,nonFixedDateApproximationConfirmed:true)).status,'coverage_not_confirmed'));
    test('terms',()=>expect(r.review(SolarTermCandidateManualReviewInput(sourceReviewApproved:true,preparationReady:true,landingReviewReady:true,sandboxSafe:true,preflightPassed:true,validatorPassed:true,crossCheckPassed:true,sourceManuallyConfirmed:true,licenseManuallyConfirmed:true,embeddingAllowedConfirmed:true,offlineConfirmed:true,nonAiGeneratedConfirmed:true,nonFixedDateApproximationConfirmed:true,coverageManuallyConfirmed:true)).status,'term_coverage_not_confirmed'));
    test('termDate',()=>expect(r.review(SolarTermCandidateManualReviewInput(sourceReviewApproved:true,preparationReady:true,landingReviewReady:true,sandboxSafe:true,preflightPassed:true,validatorPassed:true,crossCheckPassed:true,sourceManuallyConfirmed:true,licenseManuallyConfirmed:true,embeddingAllowedConfirmed:true,offlineConfirmed:true,nonAiGeneratedConfirmed:true,nonFixedDateApproximationConfirmed:true,coverageManuallyConfirmed:true,all24TermsConfirmed:true)).status,'term_date_not_confirmed'));
    test('termTime',()=>expect(r.review(SolarTermCandidateManualReviewInput(sourceReviewApproved:true,preparationReady:true,landingReviewReady:true,sandboxSafe:true,preflightPassed:true,validatorPassed:true,crossCheckPassed:true,sourceManuallyConfirmed:true,licenseManuallyConfirmed:true,embeddingAllowedConfirmed:true,offlineConfirmed:true,nonAiGeneratedConfirmed:true,nonFixedDateApproximationConfirmed:true,coverageManuallyConfirmed:true,all24TermsConfirmed:true,termDateConfirmed:true)).status,'term_time_not_confirmed'));
    test('tz',()=>expect(r.review(SolarTermCandidateManualReviewInput(sourceReviewApproved:true,preparationReady:true,landingReviewReady:true,sandboxSafe:true,preflightPassed:true,validatorPassed:true,crossCheckPassed:true,sourceManuallyConfirmed:true,licenseManuallyConfirmed:true,embeddingAllowedConfirmed:true,offlineConfirmed:true,nonAiGeneratedConfirmed:true,nonFixedDateApproximationConfirmed:true,coverageManuallyConfirmed:true,all24TermsConfirmed:true,termDateConfirmed:true,termTimeConfirmed:true)).status,'timezone_not_confirmed'));
  });

  group('references', () {
    final b = SolarTermCandidateManualReviewInput(sourceReviewApproved:true,preparationReady:true,landingReviewReady:true,sandboxSafe:true,preflightPassed:true,validatorPassed:true,crossCheckPassed:true,sourceManuallyConfirmed:true,licenseManuallyConfirmed:true,embeddingAllowedConfirmed:true,offlineConfirmed:true,nonAiGeneratedConfirmed:true,nonFixedDateApproximationConfirmed:true,coverageManuallyConfirmed:true,all24TermsConfirmed:true,termDateConfirmed:true,termTimeConfirmed:true,timezoneConfirmed:true);
    test('lichun',()=>expect(r.review(b).status,'lichun_reference_not_confirmed'));
    test('spring',()=>expect(r.review(SolarTermCandidateManualReviewInput(sourceReviewApproved:true,preparationReady:true,landingReviewReady:true,sandboxSafe:true,preflightPassed:true,validatorPassed:true,crossCheckPassed:true,sourceManuallyConfirmed:true,licenseManuallyConfirmed:true,embeddingAllowedConfirmed:true,offlineConfirmed:true,nonAiGeneratedConfirmed:true,nonFixedDateApproximationConfirmed:true,coverageManuallyConfirmed:true,all24TermsConfirmed:true,termDateConfirmed:true,termTimeConfirmed:true,timezoneConfirmed:true,lichunReferenceConfirmed:true)).status,'spring_equinox_reference_not_confirmed'));
    test('summer',()=>expect(r.review(SolarTermCandidateManualReviewInput(sourceReviewApproved:true,preparationReady:true,landingReviewReady:true,sandboxSafe:true,preflightPassed:true,validatorPassed:true,crossCheckPassed:true,sourceManuallyConfirmed:true,licenseManuallyConfirmed:true,embeddingAllowedConfirmed:true,offlineConfirmed:true,nonAiGeneratedConfirmed:true,nonFixedDateApproximationConfirmed:true,coverageManuallyConfirmed:true,all24TermsConfirmed:true,termDateConfirmed:true,termTimeConfirmed:true,timezoneConfirmed:true,lichunReferenceConfirmed:true,springEquinoxReferenceConfirmed:true)).status,'summer_solstice_reference_not_confirmed'));
    test('autumn',()=>expect(r.review(SolarTermCandidateManualReviewInput(sourceReviewApproved:true,preparationReady:true,landingReviewReady:true,sandboxSafe:true,preflightPassed:true,validatorPassed:true,crossCheckPassed:true,sourceManuallyConfirmed:true,licenseManuallyConfirmed:true,embeddingAllowedConfirmed:true,offlineConfirmed:true,nonAiGeneratedConfirmed:true,nonFixedDateApproximationConfirmed:true,coverageManuallyConfirmed:true,all24TermsConfirmed:true,termDateConfirmed:true,termTimeConfirmed:true,timezoneConfirmed:true,lichunReferenceConfirmed:true,springEquinoxReferenceConfirmed:true,summerSolsticeReferenceConfirmed:true)).status,'autumn_equinox_reference_not_confirmed'));
    test('winter',()=>expect(r.review(SolarTermCandidateManualReviewInput(sourceReviewApproved:true,preparationReady:true,landingReviewReady:true,sandboxSafe:true,preflightPassed:true,validatorPassed:true,crossCheckPassed:true,sourceManuallyConfirmed:true,licenseManuallyConfirmed:true,embeddingAllowedConfirmed:true,offlineConfirmed:true,nonAiGeneratedConfirmed:true,nonFixedDateApproximationConfirmed:true,coverageManuallyConfirmed:true,all24TermsConfirmed:true,termDateConfirmed:true,termTimeConfirmed:true,timezoneConfirmed:true,lichunReferenceConfirmed:true,springEquinoxReferenceConfirmed:true,summerSolsticeReferenceConfirmed:true,autumnEquinoxReferenceConfirmed:true)).status,'winter_solstice_reference_not_confirmed'));
  });

  group('final gates', () {
    final b = SolarTermCandidateManualReviewInput(sourceReviewApproved:true,preparationReady:true,landingReviewReady:true,sandboxSafe:true,preflightPassed:true,validatorPassed:true,crossCheckPassed:true,sourceManuallyConfirmed:true,licenseManuallyConfirmed:true,embeddingAllowedConfirmed:true,offlineConfirmed:true,nonAiGeneratedConfirmed:true,nonFixedDateApproximationConfirmed:true,coverageManuallyConfirmed:true,all24TermsConfirmed:true,termDateConfirmed:true,termTimeConfirmed:true,timezoneConfirmed:true,lichunReferenceConfirmed:true,springEquinoxReferenceConfirmed:true,summerSolsticeReferenceConfirmed:true,autumnEquinoxReferenceConfirmed:true,winterSolsticeReferenceConfirmed:true);
    test('refFixture',()=>expect(r.review(b).status,'reference_fixture_not_confirmed'));
    test('benchmark',()=>expect(r.review(SolarTermCandidateManualReviewInput(sourceReviewApproved:true,preparationReady:true,landingReviewReady:true,sandboxSafe:true,preflightPassed:true,validatorPassed:true,crossCheckPassed:true,sourceManuallyConfirmed:true,licenseManuallyConfirmed:true,embeddingAllowedConfirmed:true,offlineConfirmed:true,nonAiGeneratedConfirmed:true,nonFixedDateApproximationConfirmed:true,coverageManuallyConfirmed:true,all24TermsConfirmed:true,termDateConfirmed:true,termTimeConfirmed:true,timezoneConfirmed:true,lichunReferenceConfirmed:true,springEquinoxReferenceConfirmed:true,summerSolsticeReferenceConfirmed:true,autumnEquinoxReferenceConfirmed:true,winterSolsticeReferenceConfirmed:true,referenceFixtureConfirmed:true)).status,'benchmark_tolerance_not_confirmed'));
    test('mismatch',()=>expect(r.review(SolarTermCandidateManualReviewInput(sourceReviewApproved:true,preparationReady:true,landingReviewReady:true,sandboxSafe:true,preflightPassed:true,validatorPassed:true,crossCheckPassed:true,sourceManuallyConfirmed:true,licenseManuallyConfirmed:true,embeddingAllowedConfirmed:true,offlineConfirmed:true,nonAiGeneratedConfirmed:true,nonFixedDateApproximationConfirmed:true,coverageManuallyConfirmed:true,all24TermsConfirmed:true,termDateConfirmed:true,termTimeConfirmed:true,timezoneConfirmed:true,lichunReferenceConfirmed:true,springEquinoxReferenceConfirmed:true,summerSolsticeReferenceConfirmed:true,autumnEquinoxReferenceConfirmed:true,winterSolsticeReferenceConfirmed:true,referenceFixtureConfirmed:true,benchmarkToleranceConfirmed:true,mismatchCount:1)).status,'mismatch_exists'));
    test('warnings',()=>expect(r.review(SolarTermCandidateManualReviewInput(sourceReviewApproved:true,preparationReady:true,landingReviewReady:true,sandboxSafe:true,preflightPassed:true,validatorPassed:true,crossCheckPassed:true,sourceManuallyConfirmed:true,licenseManuallyConfirmed:true,embeddingAllowedConfirmed:true,offlineConfirmed:true,nonAiGeneratedConfirmed:true,nonFixedDateApproximationConfirmed:true,coverageManuallyConfirmed:true,all24TermsConfirmed:true,termDateConfirmed:true,termTimeConfirmed:true,timezoneConfirmed:true,lichunReferenceConfirmed:true,springEquinoxReferenceConfirmed:true,summerSolsticeReferenceConfirmed:true,autumnEquinoxReferenceConfirmed:true,winterSolsticeReferenceConfirmed:true,referenceFixtureConfirmed:true,benchmarkToleranceConfirmed:true)).status,'warnings_not_accepted'));
    test('reviewer',()=>expect(r.review(SolarTermCandidateManualReviewInput(sourceReviewApproved:true,preparationReady:true,landingReviewReady:true,sandboxSafe:true,preflightPassed:true,validatorPassed:true,crossCheckPassed:true,sourceManuallyConfirmed:true,licenseManuallyConfirmed:true,embeddingAllowedConfirmed:true,offlineConfirmed:true,nonAiGeneratedConfirmed:true,nonFixedDateApproximationConfirmed:true,coverageManuallyConfirmed:true,all24TermsConfirmed:true,termDateConfirmed:true,termTimeConfirmed:true,timezoneConfirmed:true,lichunReferenceConfirmed:true,springEquinoxReferenceConfirmed:true,summerSolsticeReferenceConfirmed:true,autumnEquinoxReferenceConfirmed:true,winterSolsticeReferenceConfirmed:true,referenceFixtureConfirmed:true,benchmarkToleranceConfirmed:true,warningsAccepted:true)).status,'reviewer_missing'));
    test('reviewedAt',()=>expect(r.review(SolarTermCandidateManualReviewInput(sourceReviewApproved:true,preparationReady:true,landingReviewReady:true,sandboxSafe:true,preflightPassed:true,validatorPassed:true,crossCheckPassed:true,sourceManuallyConfirmed:true,licenseManuallyConfirmed:true,embeddingAllowedConfirmed:true,offlineConfirmed:true,nonAiGeneratedConfirmed:true,nonFixedDateApproximationConfirmed:true,coverageManuallyConfirmed:true,all24TermsConfirmed:true,termDateConfirmed:true,termTimeConfirmed:true,timezoneConfirmed:true,lichunReferenceConfirmed:true,springEquinoxReferenceConfirmed:true,summerSolsticeReferenceConfirmed:true,autumnEquinoxReferenceConfirmed:true,winterSolsticeReferenceConfirmed:true,referenceFixtureConfirmed:true,benchmarkToleranceConfirmed:true,warningsAccepted:true,reviewer:'x')).status,'reviewed_at_missing'));
  });

  group('passed', () {
    test('all→passed',() { final o=r.review(a); expect(o.passed,true); expect(o.status,'manual_review_passed'); });
    test('readyForTrialIntegration',()=>expect(r.review(a).readyForTrialIntegration,true));
    test('productionReady',()=>expect(r.review(a).productionReady,false));
    test('publicExposure',()=>expect(r.review(a).publicExposure,false));
    test('calendarProviderIntegration',()=>expect(r.review(a).calendarProviderIntegration,false));
    test('schemaVersion',()=>expect(r.review(a).schemaVersion,'solar-term-candidate-manual-review-v0_30'));
  });
}
